using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Raft.Transport
{
    [ProtoBuf.ProtoContract]
    public class TcpMsgHandshake
    {
        public TcpMsgHandshake()
        {
        
        }

        [ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int NodeListeningPort { get; set; }

        /// <summary>
        /// Guid generated by each node
        /// </summary>
        [ProtoBuf.ProtoMember(2, IsRequired = true)]
        public long NodeUID { get; set; }
       

    }
}
